[package]
name = "hatsu"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
incremental = true
lto = "thin"
panic = "abort"
strip = "symbols"

[workspace]
members = [".", "migration"]

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }

# TODO: sea-orm "rumtime-tokio-native-tls" => "runtime-tokio-rustls"
# See https://github.com/LemmyNet/activitypub-federation-rust/issues/49

[dependencies.migration]
path = "migration"

[dependencies.tokio]
workspace = true

[dependencies]
activitypub_federation = { version = "0.4", default-features = false, features = ["axum"] }
anyhow = "1.0"
async-trait = "0.1"
axum = { version = "0.6", features = ["tokio", "macros"] }
chrono = "0.4"
dotenvy = "0.15"
enum_delegate = "0.2"
feed-rs = "1.3"
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.17"
sea-orm = { version = "0.12", features = [
  "sqlx-postgres",
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
  "macros",
  "with-chrono",
  "with-json",
  "with-uuid",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-cron-scheduler = "*"
tokio-graceful-shutdown = "0.13"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2.4", features = ["serde"] }
uuid = { version = "1.4", features = ["v4", "v7", "fast-rng", "macro-diagnostics"] }
