[package]
name = "hatsu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "migration"]

# TODO: sea-orm "rumtime-tokio-native-tls" => "runtime-tokio-rustls"
# See https://github.com/LemmyNet/activitypub-federation-rust/issues/49

[dependencies.migration]
path = "migration"

[dependencies]
activitypub_federation = { version = "0.4" }
activitystreams-kinds = "0.3"
anyhow = "1.0"
async-trait = "0.1"
axum = { version = "0.6", features = ["tokio", "macros"] }
chrono = "0.4"
dotenvy = "0.15"
futures = "0.3"
sea-orm = { version = "^0", features = [ "sqlx-postgres", "sqlx-sqlite", "runtime-tokio-native-tls", "macros", "with-chrono", "with-json" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2.4", features = ["serde"] }
