[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false
readme = "README.md"
license = "AGPL-3.0"
authors = ["藍+85CD"]
description = "Self-hosted & Fully-automated ActivityPub Bridge for Static Sites."
documentation = "https://hatsu.cli.rs"
homepage = "https://hatsu.cli.rs"
repository = "https://github.com/importantimport/hatsu"

[package]
name = "hatsu"
version.workspace = true
edition.workspace = true
publish.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"

[workspace]
members = [".", "migration"]

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }

# TODO: sea-orm "rumtime-tokio-native-tls" => "runtime-tokio-rustls"
# See https://github.com/LemmyNet/activitypub-federation-rust/issues/49

[dependencies.migration]
path = "migration"

[dependencies.tokio]
workspace = true

[dependencies]
activitypub_federation = { version = "0.4", default-features = false, features = ["axum"] }
anyhow = "1.0"
async-trait = "0.1"
axum = { version = "0.6", features = ["tokio", "macros"] }
axum-extra = { version = "0.8", features = ["query", "typed-routing"]}
chrono = "0.4"
dotenvy = "0.15"
enum_delegate = "0.2"
feed-rs = "1.3"
markdown = "1.0.0-alpha.13"
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.17"
sea-orm = { version = "0.12", features = [
  "sqlx-postgres",
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
  "macros",
  "with-chrono",
  "with-json",
  "with-uuid",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snmalloc-rs = "0.3"
tokio-cron-scheduler = "*"
tokio-graceful-shutdown = "0.13"
tracing = { version = "0.1" }
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
url = { version = "2.4", features = ["serde"] }
urlencoding = "2"
utoipa = { version = "4", features = ["axum_extras", "url", "uuid"]}
# TODO: dev-dependencies
utoipa-swagger-ui = { version = "4", features = ["axum"] }
uuid = { version = "1.4", features = ["v4", "v7", "fast-rng", "macro-diagnostics"] }
