[build]
default-target = "x86_64-unknown-linux-musl"
pre-build = [
    # "dpkg --add-architecture $CROSS_DEB_ARCH",
    # "apt update && apt -y install libssl-dev:$CROSS_DEB_ARCH",
    "apt update && apt -y install openssl libssl-dev pkg-config mold",
]
