services:
  hatsu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: debug
    container_name: hatsu
    env_file: .env
    volumes:
      # - ./.env:/app/.env
      - ./hatsu.sqlite3:/app/hatsu.sqlite3
    ports:
      - 3939:3939
