version: "3"

services:
  hatsu:
    build:
      args:
        PROFILE: debug
      context: .
      dockerfile: Dockerfile
    container_name: hatsu
    ports:
      - 3939:3939
    volumes:
      - ./.env:/app/.env
      - ./hatsu.sqlite3:/app/hatsu.sqlite3
