[unstable]
codegen-backend = true
# profile-rustflags = true

[rust]
lld = true

[profile.dev]
codegen-backend = "cranelift"

# x86_64-unknown-linux-gnu (lld)
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

# Enable UUID Unstable Features
# https://docs.rs/uuid/1.4.0/uuid/index.html#unstable-features
[target.'cfg(all())']
rustflags = ["--cfg", "uuid_unstable"]

# x86_64-v2 (Intel Nehalem / AMD Jaguar and above)
# https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels
[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=x86-64-v2"]

# aarch64 (ARM Neon)
[target.'cfg(target_arch = "aarch64")']
rustflags = ["-C", "target-feature=+neon"]
