version: "3"

services:
  hatsu:
    container_name: hatsu
    image: ghcr.io/importantimport/hatsu:nightly
    restart: unless-stopped
    ports:
      - 3939:3939
    # env_file:
    #   - .env
    environment:
      - DATABASE_URL=sqlite://hatsu.sqlite3
      - HATSU_LISTEN_HOST=0.0.0.0
      - HATSU_DOMAIN={{your-domain-here}}
      - HATSU_PRIMARY_ACCOUNT={{your-domain-here}}
    volumes:
      # - ./.env:/app/.env
      - ./hatsu.sqlite3:/app/hatsu.sqlite3
