name: GitHub Pages

on:
  push:
    paths:
      - 'docs/src/**'
      - 'docs/book.toml'
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: docs

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
          
      - run: cargo install mdbook-catppuccin mdbook-linkcheck mdbook-toc

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          cname: hatsu.kwaa.dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
