name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: just fmt --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: rui314/setup-mold@v1
      - uses: taiki-e/install-action@just
      - uses: mozilla-actions/sccache-action@v0.0.3
      - run: just fmt --check

  lint:
    name: just lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: rui314/setup-mold@v1
      - uses: taiki-e/install-action@just
      - uses: mozilla-actions/sccache-action@v0.0.3
      - run: just lint

  build:
    name: just build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: rui314/setup-mold@v1
      - uses: taiki-e/install-action@just
      - uses: mozilla-actions/sccache-action@v0.0.3
      - run: just build
      - uses: actions/upload-artifact@v4
        with:
          name: hatsu
          path: target/release/hatsu
